In [31]:
#1. Loading and Preprocessing (2 marks):
#● Load the California Housing dataset using the fetch_california_housing function from sklearn.
#● Convert the dataset into a pandas DataFrame for easier handling. Handle missing values (if any) and perform necessary feature scaling (e.g., standardization).
#● Explain the preprocessing steps you performed and justify why they are necessary for this dataset.

In [32]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
housing = fetch_california_housing(as_frame=True)
df = housing.frame
print(df)

# Check for missing values
print(df.isnull().sum())

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
...       ...       ...       ...        ...         ...       ...       ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

       Longitude  MedHouseVal
0        -122.23        4.526
1        -122.22        3.585
2        -122.24        3.521
3        -122.25        3.413
4        -122.25        3.422
...          ...          ...
20635    -121.09        0.781
20636    -121.21        0.771
20637    -121.22        0.923
20638    -121.32        0.847
20639    -121.24        0.894

[20640 rows x 9 columns]
MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [33]:
# Features and target
X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]

# Feature scaling 
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,2.344766,0.982143,0.628559,-0.153758,-0.974429,-0.049597,1.052548,-1.327835
1,2.332238,-0.607019,0.327041,-0.263336,0.861439,-0.092512,1.043185,-1.322844
2,1.782699,1.856182,1.155620,-0.049016,-0.820777,-0.025843,1.038503,-1.332827
3,0.932968,1.856182,0.156966,-0.049833,-0.766028,-0.050329,1.038503,-1.337818
4,-0.012881,1.856182,0.344711,-0.032906,-0.759847,-0.085616,1.038503,-1.337818

In [34]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(X_train, X_test, y_train, y_test)

         MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
14196 -0.321654  0.346478 -0.166259  -0.190451    0.772251  0.059808
8267  -0.030620  1.617807 -0.386181  -0.117472   -0.098440 -0.128306
17445  0.150349 -1.957806  0.087641  -0.235400   -0.450778 -0.033453
14265 -1.014947  0.584852 -0.576442  -0.132670   -0.006602  0.088940
2271  -0.166583  1.141059  0.339282   0.079205   -0.486983 -0.074203
...         ...       ...       ...        ...         ...       ...
11284  1.315592  0.505394  0.282943  -0.359587   -0.677723 -0.003697
11964 -0.431983  0.346478  0.581864   0.364661    0.289220  0.080261
5390  -0.492832  0.584852 -0.582949  -0.035828    0.291870  0.025170
860    0.973025 -1.083767  0.390584  -0.060554    0.310414  0.010422
15795 -0.681749  1.856182 -0.819050  -0.079973    1.053944 -0.092623

       Latitude  Longitude
14196 -1.367976   1.267645
8267  -0.871699   0.703627
17445 -0.455012  -0.454356
14265 -1.377340   1.227714
2271   0.537543  -0.114948
...         ...        ...
11284 -0.867017   0.803453
11964 -0.754652   1.067992
5390  -0.749970   0.593818
860    0.912092  -1.193070
15795  1.001048  -1.422670

[16512 rows x 8 columns]          MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
20046 -1.152489 -0.289187 -0.499896  -0.156976   -0.029562  0.077681
3024  -0.705015  0.108104 -0.157477   0.204301    0.123206 -0.037634
15663 -0.205588  1.856182 -0.586814   0.188231   -0.101972 -0.164679
20484  0.982710 -0.924851  0.296929  -0.161370    0.246834  0.035990
9814  -0.076678  0.425936  0.025864  -0.144836   -0.320086 -0.056520
...         ...       ...       ...        ...         ...       ...
15362  0.386535 -1.004309  0.635869  -0.063945   -0.065767 -0.007868
16623 -0.602214 -0.050812  0.284108   0.337756    0.198266 -0.070310
18086  2.820927 -0.289187  0.731040  -0.315451    0.140868 -0.026976
2144  -0.571473  0.584852 -0.056574  -0.239614   -0.175266 -0.046414
3665  -0.167689 -0.924851 -0.582092  -0.133347    0.216810  0.063477

       Latitude  Longitude
20046  0.200449   0.279366
3024  -0.230283   0.054757
15663  1.015093  -1.432653
20484 -0.632923   0.424114
9814   0.462633  -1.178096
...         ...        ...
15362 -1.063655   1.172810
16623 -0.127282  -0.629052
18086  0.785682  -1.237992
2144   0.532861  -0.094982
3665  -0.661015   0.598809

[4128 rows x 8 columns] 14196    1.030
8267     3.821
17445    1.726
14265    0.934
2271     0.965
         ...
11284    2.292
11964    0.978
5390     2.221
860      2.835
15795    3.250
Name: MedHouseVal, Length: 16512, dtype: float64 20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: MedHouseVal, Length: 4128, dtype: float64

In [35]:
#2. Regression Algorithm Implementation (5 marks):
#● Implement the following regression algorithms:
#○ Linear Regression
#○ Decision Tree Regressor
#○ Random Forest Regressor
#○ Gradient Boosting Regressor
#○ Support Vector Regressor (SVR)
#● For each algorithm: Provide a brief explanation of how it works. Explain why it might be suitable for this dataset.

In [36]:
#LinearRegression
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

In [37]:
#Linear Regression model, which works by finding the "best-fit line" that minimizes the distance between your data points and the predicted values. It learns the mathematical relationship between your input features (X_train) and the target variable (y_train) by assigning weights to each feature. Once the model is "fitted," it uses that learned equation to predict outcomes (y_pred_lr) for new, unseen data (X_test).

In [38]:
#DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

In [39]:
#A Decision Tree Regressor works by repeatedly splitting your data into smaller groups based on specific "if-then" rules. It builds a tree-like structure where each branch represents a decision based on a feature, leading down to "leaf" nodes. For regression, the final prediction is usually the average value of the training samples in that specific leaf. This approach allows the model to capture complex, non-linear relationships that a simple straight line might miss.

In [40]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def evaluate(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, mae, r2


#Evaluate Models

lr_metrics = evaluate(y_test, y_pred_lr)
dt_metrics = evaluate(y_test, y_pred_dt)

print("Linear Regression", lr_metrics)
print("Decision Tree:", dt_metrics)

Linear Regression (0.5558915986952442, 0.5332001304956565, 0.575787706032451)
Decision Tree: (0.4942716777366763, 0.4537843265503876, 0.6228111330554302)

In [41]:
#3. Model Evaluation and Comparison (2 marks):
#● Evaluate the performance of each algorithm using the following metrics:
#○ Mean Squared Error (MSE)
#○ Mean Absolute Error (MAE)
#○ R-squared Score (R2)
#● Compare the results of all models and identify: The best-performing algorithm with justification and the worst-performing algorithm with reasoning.

In [42]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree"],
    "MSE": [lr_metrics[0],dt_metrics[0]],
    "MAE": [lr_metrics[1],dt_metrics[1]],
    "R2 Score": [lr_metrics[2],dt_metrics[2]]
})
results

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.494272  0.453784  0.622811

In [43]:
#Based on the metrics, the Decision Tree is the best-performing model because it achieved the lowest error rates (MSE: 0.494, MAE: 0.453) and the highest score (0.622), indicating a better fit for the data. Conversely, Linear Regression is the worst-performing model, as it produced higher errors and a lower score (0.576), suggesting that a simple linear relationship is less effective at capturing the patterns in this dataset.